apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hopon-ingress
  namespace: hopon
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
        - hopon.mn
        - api.hopon.mn
      secretName: hopon-tls
  rules:
    - host: hopon.mn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 80
    - host: api.hopon.mn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway-service
                port:
                  number: 3000
